/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppClientRouteImport } from './routes/_authenticated/app.client'
import { Route as AuthenticatedAppProxiesRouteImport } from './routes/_authenticated/app.proxies'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClientRoute = AuthenticatedAppClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProxiesRoute = AuthenticatedAppProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/app/client': typeof AuthenticatedAppClientRoute
  '/app/proxies': typeof AuthenticatedAppProxiesRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/client': typeof AuthenticatedAppClientRoute
  '/app/proxies': typeof AuthenticatedAppProxiesRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/app/client': typeof AuthenticatedAppClientRoute
  '/_authenticated/app/proxies': typeof AuthenticatedAppProxiesRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/invite/$token'
    | '/app/client'
    | '/app/proxies'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/invite/$token'
    | '/app/client'
    | '/app/proxies'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/invite/$token'
    | '/_authenticated/app/client'
    | '/_authenticated/app/proxies'
    | '/_authenticated/app/team'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/client': {
      id: '/_authenticated/app/client'
      path: '/client'
      fullPath: '/app/client'
      preLoaderRoute: typeof AuthenticatedAppClientRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/proxies': {
      id: '/_authenticated/app/proxies'
      path: '/proxies'
      fullPath: '/app/proxies'
      preLoaderRoute: typeof AuthenticatedAppProxiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppClientRoute: typeof AuthenticatedAppClientRoute
  AuthenticatedAppProxiesRoute: typeof AuthenticatedAppProxiesRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppClientRoute: AuthenticatedAppClientRoute,
  AuthenticatedAppProxiesRoute: AuthenticatedAppProxiesRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
